### ISSUE TITLE
Out of memory problem

### ISSUE THREAD

**Issue by remedge** [SNakano/CacheStore#8]
We have memory leak on server: 

PHP Fatal error:  Out of memory (allocated 122683392) (tried to allocate 108204625 bytes) in /../vendor/snakano/cache-store/src/Domino/CacheStore/Storage/Redis.php on line 93

Server have 2048mb memory per php process. Is it not enough?

**Comment by bizmate** [comment]
Just pointing to the PHP Fatal error and trying to troubleshoot it wont help fixing the problem. The problem here is in your code. You are using the library in the wrong way as it is very unlikely that a process should reach such an high usage of memory. 

If after you troubleshoot you code you still think you are using the CentralStorage in the correct and most efficient way possible then think about increasing memory.

It is really specific to your application needs and nothing to do with the library as the error is caused by 1) the process you are generating a huge amount of buffered memory and using lots of resources, 2) your server memory is limited to a certain amount so any process using more memory should be optimised or memory increased. 

Please close the ticket as this is irrelevant from the library

**Comment by remedge** [comment]
Thanks for your answer. I figured out that it was the first way you describe - process is generating a huge amount of buffered memory. Need to find way to optimize the logic.

 Closing.
